//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Occupation
    {
        public int ID { get; set; }
        public string OccupationType { get; set; }
        public int RatingID { get; set; }
    
        public virtual OccupationRating OccupationRating { get; set; }
    }
}
